/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pelajar;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
/**
 *
 * @author ACER
 */
public class Siswu extends javax.swing.JFrame {
     DefaultTableModel tabModel;
    ResultSet Rssiswu=null;
    /**
     * Creates new form Siswu
     */
    public Siswu() {
        initComponents();
         Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize=this.getSize();
        if(frameSize.height > screenSize.height){
        frameSize.height=screenSize.height;
        }
        if(frameSize.width > screenSize.width){
        frameSize.width=screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
        (screenSize.height = screenSize.height) / 20); 
        
        tampilData();
        SetEditOff();
    }
    
    private void tampilData(){
        try{    
            Object[] judul_kolom = {"NIS", "Nama", "Kelas", "Jurusan",};
            tabModel=new DefaultTableModel(null,judul_kolom);
            TabelSiswu.setModel(tabModel);
            
            Connection conn=(Connection)Koneksi.KoneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            Rssiswu=stt.executeQuery("SELECT * from siswu ");  
            while(Rssiswu.next()){
                Object[] data={
                    Rssiswu.getString("NIS"),
                    Rssiswu.getString("Nama"),
                    Rssiswu.getString("Kelas"),
                    Rssiswu.getString("Jurusan"),        
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
        // disable button
        jButtonSave.setEnabled(false);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonCancel.setEnabled(false);
    }
    
    //menampilkan data ke form saat data pada tabel di klik 
   void tblKeForm(){
        jTextNIS.setText(tabModel.getValueAt(TabelSiswu.getSelectedRow(),0)+"");
        jTextNama.setText(tabModel.getValueAt(TabelSiswu.getSelectedRow(),1)+"");
        jTextKelas.setText(tabModel.getValueAt(TabelSiswu.getSelectedRow(),2)+"");
        jComboJurusan.setSelectedItem(tabModel.getValueAt(TabelSiswu.getSelectedRow(),3)+"");
        
        jButtonUpdate.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonSave.setEnabled(false);
    }

    //membersihkan form
   private void BersihData(){
        jTextNIS.setText("");
        jTextNama.setText("");
        jTextKelas.setText(""); 
        jComboJurusan.setSelectedIndex(0);
    } 
   
   //disable form
   private void SetEditOff(){
        jTextNIS.setEnabled(false);
        jTextNama.setEnabled(false);
        jTextKelas.setEnabled(false);
        jComboJurusan.setEnabled(false);
   }
   
   private void seteditOn(){
        jTextNIS.setEnabled(true);
        jTextNama.setEnabled(true);
        jTextKelas.setEnabled(true);
        jComboJurusan.setEnabled(true);
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jLabelNIS = new javax.swing.JLabel();
        jTextNIS = new javax.swing.JTextField();
        jLabelNama = new javax.swing.JLabel();
        jTextNama = new javax.swing.JTextField();
        jLabelKelas = new javax.swing.JLabel();
        jTextKelas = new javax.swing.JTextField();
        jLabelJurusan = new javax.swing.JLabel();
        jComboJurusan = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelSiswu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHeader.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelHeader.setText("Data Siswa");

        jLabelNIS.setText("NIS");

        jLabelNama.setText("Nama");

        jLabelKelas.setText("Kelas");

        jLabelJurusan.setText("Jurusan");

        jComboJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RPL", "TKJ", "TKRO", "OTKP" }));

        jButtonAdd.setText("AddNew");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        TabelSiswu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Kelas", "Jurusan"
            }
        ));
        TabelSiswu.setCellSelectionEnabled(true);
        TabelSiswu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelSiswuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelSiswu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButtonSave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelNIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNama, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                            .addComponent(jLabelKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJurusan))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabelHeader))
                            .addComponent(jButtonAdd)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextNIS)
                                .addComponent(jTextNama)
                                .addComponent(jTextKelas)
                                .addComponent(jComboJurusan, 0, 169, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addGap(0, 280, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelHeader)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNIS)
                            .addComponent(jTextNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelKelas)
                            .addComponent(jTextKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJurusan)
                            .addComponent(jComboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButtonAdd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCancel))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
         BersihData();
        jTextNIS.requestFocus();
        jButtonSave.setEnabled(true);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        seteditOn();                          
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        String NIS=jTextNIS.getText();
        String Nama=jTextNama.getText();
        String Kelas=jTextKelas.getText();
        String Jurusan=jComboJurusan.getSelectedItem().toString();
        
         

        if (NIS.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"NIS tidak boleh kosong");
            jTextNIS.requestFocus();
        }else if (Nama.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama tidak boleh kosong");
            jTextNama.requestFocus();
        }else if (Kelas.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Kelas tidak boleh kosong");
            jTextKelas.requestFocus();
        }else if (Jurusan.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jurusan tidak boleh kosong");
            jComboJurusan.requestFocus();
        }
        else if (!(new Scanner(Kelas).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Kelas harus angka");
            jTextKelas.requestFocus();
        }else{
            try{
                Connection conn=(Connection)Koneksi.KoneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("insert into Siswu(NIS,Nama,Kelas,Jurusan)"+"VALUES('"+NIS+"','"+Nama+"','"+Kelas+"','"+Jurusan+"')");
                BersihData();
                tampilData();
                SetEditOff();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
         String NIS=jTextNIS.getText();
        String Nama=jTextNama.getText();
        String Kelas=jTextKelas.getText();
        String Jurusan=jComboJurusan.getSelectedItem().toString();

       
        if (NIS.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"NIS tidak boleh kosong");
            jTextNIS.requestFocus();
        }else if (Nama.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama tidak boleh kosong");
            jTextNama.requestFocus();
        }else if (Kelas.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Kelas tidak boleh kosong");
            jTextKelas.requestFocus();
             }else if (Jurusan.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jurusan tidak boleh kosong");
            jComboJurusan.requestFocus();
       
        }
        else if (!(new Scanner(Kelas).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Kelas harus angka");
            jTextKelas.requestFocus();
        
        }else{
            try{
                Connection conn=(Connection)Koneksi.KoneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("UPDATE Siswu SET Nama='"+Nama+"', Kelas='"+Kelas+"', "+"Jurusan='"+Jurusan+"' WHERE NIS='"+NIS+"'");
                BersihData();
                tampilData();
                SetEditOff();
                JOptionPane.showMessageDialog(this,"Data berhasil diubah","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Ubah data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
                                            
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
         String NIS=jTextNIS.getText();

        if (NIS.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"NIS tidak boleh kosong");
            jTextNIS.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Connection conn=(Connection)Koneksi.KoneksiDB();
            Statement stt=conn.createStatement();
            stt.executeUpdate("DELETE FROM siswu WHERE NIS='"+NIS+"'");
            BersihData();
            tampilData();
            SetEditOff();
            JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        }                                             

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
         BersihData();
        jButtonSave.setEnabled(false);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        SetEditOff();
                                    
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void TabelSiswuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelSiswuMouseClicked
        // TODO add your handling code here:
         seteditOn();
        jTextNIS.setEnabled(false);
        tblKeForm();
    }//GEN-LAST:event_TabelSiswuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siswu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelSiswu;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboJurusan;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelJurusan;
    private javax.swing.JLabel jLabelKelas;
    private javax.swing.JLabel jLabelNIS;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextKelas;
    private javax.swing.JTextField jTextNIS;
    private javax.swing.JTextField jTextNama;
    // End of variables declaration//GEN-END:variables

   
}
